// lib/src/features/habits/domain/habit_model.dart

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:hive_flutter/hive_flutter.dart';

part 'habit_model.freezed.dart'; // Generated by freezed
part 'habit_model.g.dart';       // Generated by json_serializable & hive_generator

@freezed
@HiveType(typeId: 0) // Unique typeId for Hive
class Habit with _$Habit {
  const factory Habit({
    @HiveField(0) required String id,
    @HiveField(1) required String title,
    @HiveField(2) String? description,
    @HiveField(3) required String category,
    @HiveField(4) required DateTime startDate,
    // Note: For complex objects like 'schedule', you might need a separate model
    // with its own TypeAdapter. For now, we'll keep it simple.
    @HiveField(5) required List<int> weekdays, // e.g., [1, 3, 5] for Mon, Wed, Fri
    @HiveField(6) required DateTime createdAt,
    @HiveField(7) DateTime? updatedAt,
  }) = _Habit;

  factory Habit.fromJson(Map<String, dynamic> json) => _$HabitFromJson(json);
}